version: '3'

output: prefixed

vars:  # Define variables for clarity and reusability
  K3D_CONFIG: ./k8s/k3d/k3d-config.yaml
  CLUSTER_NAME: aspire-cluster

env:
  files:
    - .env

tasks:
  run:
    desc: "Run the dotnet project"
    cmds:
      - dotnet run --project app-host/CoffeeShop.AppHost.csproj
    sources:
      - "**/*.cs"
      - "**/*.csproj"
    shopt: 
      - expand_aliases
    env:
      include:
        - .env
    
  build:
    desc: "Build the dotnet solution"
    cmds:
      - dotnet build coffeeshop-aspire.sln
    sources:
      - "**/*.cs"
    shopt: 
      - expand_aliases
    env:
      include:
        - .env

  # ---------------------------------------------------------------------------
  # region: Cluster

  cluster-create:
    cmds:
      - k3d cluster create --config {{.K3D_CONFIG}} {{.CLI_ARGS}}

  cluster-delete:
    cmds:
      - k3d cluster delete {{.CLUSTER_NAME}} {{.CLI_ARGS}}

  # ---------------------------------------------------------------------------
  # region: Cluster Node

  cluster-node-create:
    cmds:
      - k3d node create --cluster {{.CLUSTER_NAME}} {{.CLI_ARGS}} --verbose

  cluster-node-delete:
    cmds:
      - k3d node delete {{.CLI_ARGS}} --verbose
      # - k3d node delete --cluster {{.CLUSTER_NAME}} {{.CLI_ARGS}}

  # ---------------------------------------------------------------------------
  # region: Cluster Start/Stop

  cluster-start:
    cmds:
      - k3d cluster start {{.CLUSTER_NAME}} {{.CLI_ARGS}}

  cluster-stop:
    cmds:
      - k3d cluster stop {{.CLUSTER_NAME}} {{.CLI_ARGS}}

  # ---------------------------------------------------------------------------
  # region: Cluster Images

  cluster-images-export:
    dir: k8s/scripts/
    cmds:
      - chmod u+x ./kubectl-list-pod-images.sh
      - cmd: ./kubectl-list-pod-images.sh {{.CLI_ARGS}}
        ignore_error: true

  cluster-images-import:
    dir: k8s/scripts/
    cmds:
      - chmod u+x ./k3d-image-import.sh
      - ./k3d-image-import.sh {{.CLI_ARGS}}

  cluster-images-import-single:
    cmds:
      - docker pull {{.CLI_ARGS}}
      - k3d image import --cluster {{.CLUSTER_NAME}} --mode "auto" {{.CLI_ARGS}}

  # ---------------------------------------------------------------------------
  # region: Cluster Reset

  cluster-reset:  # Combines multiple Makefile targets
    cmds:
      - task: cluster-images-export
      - task: cluster-delete
      - task: cluster-create
      - task: cluster-images-import

  # ---------------------------------------------------------------------------
  # region: Tilt

  tilt-up:
    cmds:
      - tilt up --file ./Tiltfile --stream --verbose {{.CLI_ARGS}}

  tilt-ci:
    cmds:
      - tilt ci --file ./Tiltfile --verbose {{.CLI_ARGS}}

  tilt-stop:
    cmds:
      - pkill -9 tilt

  tilt-update:
    cmds:
      - curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
