# Reference: https://kubernetes.io/docs/concepts/storage/storage-classes/
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile
provisioner: rancher.io/local-path
reclaimPolicy: Delete

# Reference: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode
volumeBindingMode: WaitForFirstConsumer
# volumeBindingMode: Immediate

parameters:
  pathPattern: "/tmp/${pvc.namespace}/${pvc.name}"
  nodeAffinityLabel: kubernetes.io/hostname
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: rancher.io/local-path
reclaimPolicy: Delete

# Reference: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode
volumeBindingMode: WaitForFirstConsumer
# volumeBindingMode: Immediate

parameters:
  pathPattern: "/tmp/${pvc.namespace}/${pvc.name}"
  nodeAffinityLabel: kubernetes.io/hostname
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed
provisioner: rancher.io/local-path
reclaimPolicy: Delete

# Reference: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode
volumeBindingMode: WaitForFirstConsumer
# volumeBindingMode: Immediate

parameters:
  pathPattern: "/tmp/${pvc.namespace}/${pvc.name}"
  nodeAffinityLabel: kubernetes.io/hostname
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-nfs-premium
provisioner: rancher.io/local-path
reclaimPolicy: Delete

# Reference: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode
volumeBindingMode: WaitForFirstConsumer
# volumeBindingMode: Immediate

parameters:
  pathPattern: "/tmp/${pvc.namespace}/${pvc.name}"
  nodeAffinityLabel: kubernetes.io/hostname
