FROM mcr.microsoft.com/devcontainers/dotnet:8.0

# Install sudo command for script compatibility
RUN apt-get update && apt-get install -y sudo git bash bash-completion

# Install dos2unix command
RUN apt-get install -y dos2unix
