
watch_file(paths=".")

# Build the Docker image
docker_build(
    ref="mycompanycontainers.azurecr.io/brown-bag/minimal-api:latest",
    context=".",
    build_args={},
    dockerfile="Dockerfile",
    live_update=[
        # Sync local changes to remote container
        sync('main.csx', '/app/main.csx'),
    ],
)

# Deploy kubernetes objects
k8s_yaml(
    yaml="k8s.yaml"
)
